import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@frontend/styles/Home.module.css";
import { useState } from "react";
import getConfig from "next/config";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [secrets, setSecrets] = useState([]);
  const [publicSecret, setPublicSecret] = useState(null);

  const { PUBLIC_SECRET } = getConfig().publicRuntimeConfig;

  console.log("PUBLIC_SECRET", PUBLIC_SECRET);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div
          style={{
            marginTop: "4rem",
          }}
          onClick={async () => {
            const res = await fetch("/api/secrets");
            const data = await res.json();
            setSecrets(data);
          }}
        >
          Click me for server side secrets (this will return secrets from the
          server side only - shouldnt be done in live but just an example)
          <span className={styles.secret}>🤫</span>
        </div>

        <div
          style={{
            marginTop: "8rem",
          }}
        >
          {JSON.stringify(secrets, null, 2)}
        </div>

        <div>Client side secret is: {PUBLIC_SECRET}</div>
      </main>
    </>
  );
}
